### PR TITLE
Dispose subscription when client disconnected

### PR DESCRIPTION
**Pull request by johannesegger**
Feels a bit dirty to not put that in a `use` or `try/finally` block, but `use` doesn't support `IAsyncDisposable` and `try/finally` doesn't support asyncs it seems. Any idea?

### CODE REVIEW

**Review by dbrattli — APPROVED** [review]
You might want to add an issue for F# for the `use!` keyword for us to support this. Ref similar issue for C# https://github.com/dotnet/csharplang/issues/43 

Just checked that there is already an `use!` keyword in F#, so we could perhaps make an overload for `async` that can use `IAsyncDisposable`.

**Comment by johannesegger** [comment]
Ok thanks, I need to look up on how that works. However, you should be able to edit this PR if you want to complete this, just sayin' :-)

**Comment by johannesegger** [comment]
Hm just thought about it. Isn't `use!` only possible when something returns `Async<IDisposable>`, i.e. the operation to get that disposable is async, but the disposal itself is sync, isn't it?

**Comment by johannesegger** [comment]
I think it would be [try...finally!](https://github.com/fsharp/fslang-suggestions/issues/651).

**Comment by dbrattli** [comment]
I was thinking about something like this. And the link you provided explains why I cannot await in the finally handler:

```fs
type Microsoft.FSharp.Control.AsyncBuilder with
    member x.Using (resource : 'T :> IAsyncDisposable, binder: 'T -> Async<'a>) : Async<'a> =
        async {
            let result =
                try
                    binder resource
                finally
                    resource.DisposeAsync () |> Async.RunSynchronously
            return! result
        }
```

But it somehow isn't working: "The type 'IAsyncDisposable' is not compatible with the type 'IDisposable'".

**Comment by johannesegger** [comment]
Do you really want it to run synchronously? I would probably prefer async disposal with work-arounds like we had in C# when `await` wasn't possible in catch/finally (e.g. like [this](https://stackoverflow.com/a/8869589/1293659) one).

**Comment by dbrattli** [comment]
No, don't want that, but if the overload doesn't work then it doesn't matter anyways.

**Comment by johannesegger** [comment]
Ok, maybe it's just something small. Unfortunately I don't have any experience with writing computation expressions.

**Comment by johannesegger** [comment]
It [looks like](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions) `Using` must have the signature `'T * ('T -> M<'U>) -> M<'U> when 'U :> IDisposable` with `M` being `Async` in our case and `U` being constrained to something that implements `IDisposable`. So I don't think there's much room for `IAsyncDisposable`, right?

**Comment by dbrattli** [comment]
Yes, I think you are right. Makes me think if we should let subscriptions be both IDisposable and IAsyncDisposable. Many disposable scenarios are synchronous, but there could also be some cases where you need to contact some (statefull) service to do cleanup

**Comment by johannesegger** [comment]
Yes, I fully agree that there are async disposables. C# is currently discussing about [async streams](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/async-streams), so it might get something like that soon. F# looks like it's a bit further away from stuff like this. But subscriptions being both `IDisposable` and `IAsyncDisposable` might be weird - one can always call `d.DisposeAsync() |> Async.RunSynchronously` as you did earlier in this thread. IMO the overall best thing in F# would be 

> ... [try...finally!](https://github.com/fsharp/fslang-suggestions/issues/651).

whereas the best thing we can currently do is 

> ... work-arounds like we had in C# when `await` wasn't possible in catch/finally (e.g. like [this](https://stackoverflow.com/a/8869589/1293659) one).

**Comment by dbrattli** [comment]
Yes, agree.

**Comment by johannesegger** [comment]
I added a reusable function `useAsyncDisposable` that executes an async workflow, catches any exceptions using `Async.Catch`, disposes the async disposable and rethrows any exception. I didn't really try it though to be honest. I also rebased on master.

**Comment by dbrattli** [comment]
Thanks for fixing.

**Comment by johannesegger** [comment]
Thanks for merging 👍

**Pull request merged**
