### PR TITLE
Shutdown gracefully

### PR DESCRIPTION
**Pull request by johannesegger**
Cancel websocket connection when application is shutting down. Otherwise ASP.NET Core kills us after the [shutdown timeout](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1#shutdown-timeout).

### CODE REVIEW

**Review by dbrattli — APPROVED** [review]
Looks good. Thanks for fixing!

**Comment by johannesegger** [comment]
You're welcome. Thanks for merging 👍

**Comment by dbrattli** [comment]
FYI: Will produce a new NuGet later today

**Comment by johannesegger** [comment]
Very much appreciated, thanks.

**Pull request merged**
